### ISSUE TITLE
Mesh export

### ISSUE THREAD

**Issue by jclarkk** [magic-research/magic-boost#2]
Should we use the [regular methods](https://github.com/threestudio-project/threestudio#export-meshes) for extracting mesh via threestudio or is there a better way? Right now it can only export using 256_tets.npz which is really heavy (100+MB OBJ) and couldn't export textures.

**Comment by yf1019** [comment]
Hi, currently we only support using mesh extraction method in the threestudio. We are working on the improvement of mesh extraction code, and will update it soon.

**Comment by jclarkk** [comment]
Thanks for the reply. Are you able to get texture or vertex colors with the current exporter? It doesn't work for me.

**Comment by yf1019** [comment]
Sure, you should get a textured mesh following this:
https://github.com/threestudio-project/threestudio?tab=readme-ov-file#export-meshes, you may need to adjust the isosurface threshold to be higher.
![demo05](https://github.com/magic-research/magic-boost/assets/44568791/809c5cd9-489f-41c9-8fde-75220e66938a)

**Comment by jclarkk** [comment]
Thanks! I'm getting a lot of artifacts after the refinement process but I'll open a different issue for that.

**Comment by flyingdoubleG** [comment]
> Sure, you should get a textured mesh following this: https://github.com/threestudio-project/threestudio?tab=readme-ov-file#export-meshes, you may need to adjust the isosurface threshold to be higher. ![demo05](https://private-user-images.githubusercontent.com/44568791/334344526-809c5cd9-489f-41c9-8fde-75220e66938a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODgwMjksIm5iZiI6MTcxNzE4NzcyOSwicGF0aCI6Ii80NDU2ODc5MS8zMzQzNDQ1MjYtODA5YzVjZDktNDg5Zi00MWM5LThmZGUtNzUyMjBlNjY5MzhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDIwMzUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNTM1NWQ5OWZhZWMxNGE1OGY5YmIwNTM4ZTcxNDIxNDY5N2MwNTdkMjA0YWM2YjE5OGY1MTExZTMxNTM3ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sVwBL06s0OiGDGGKbjfrzc1OTVNqnqSzDfwTcKKbfUw)

what's the value of isosurface_threshold you use here
