### ISSUE TITLE
Rotate meshes from InstantMesh before refinement?

### ISSUE THREAD

**Issue by snowflakewang** [magic-research/magic-boost#3]
Hello, thank you for your brilliant work in texture boosting of 3D generation!

I use **InstantMesh** as the 3D generation base model and obtain multi-view images and their corresponding mesh. Then I run the Mesh-to-NeRF stage and get this result. It seems reversed up and down. So, should I rotate the mesh before input? If I indeed need to rotate it, what criteria should I follow?
Or have you met such problems before when using **InstantMesh**?
![it1000-0](https://github.com/magic-research/magic-boost/assets/83908155/f9515090-2f18-4fe9-8f6a-7b89af8c8e6a)

Thank you! :)

**Comment by yf1019** [comment]
Hi, Thank you for reporting the bug. We just found that Instantmesh has updated the mesh extraction code but we did the test in the old version. We have fixed the bug, please try the lastest code.

**Comment by snowflakewang** [comment]
Hello, thank you for your revision. I have changed "+z" to "-z" in **configs/mesh-fitting-instantmesh.yaml** following your latest commit. But I still meet this problem.
![it1000-0](https://github.com/magic-research/magic-boost/assets/83908155/2b005346-a4d6-416d-be08-6fe26b803f51)

**Comment by yf1019** [comment]
Hi, thanks for the response. I just pushed a new one that should fix the bug. Give it a try~

**Comment by snowflakewang** [comment]
Hello, I have tried your new revision. It works well in the Mesh-to-NeRF stage, as the Figure 1.
![it1000-0](https://github.com/magic-research/magic-boost/assets/83908155/0d55526e-6828-4538-85a5-ae5a5e5aa91b)


But a new problem arises. The refinement stage seems to introduce artifacts as the Figure 2, which is an image file called **it2500-0_du_input.png**. I wonder whether some misalignment between reference images and the NeRF leads to such artifacts.
![it2500-0_du_input](https://github.com/magic-research/magic-boost/assets/83908155/481a8ab0-528b-4702-9267-a9c1af964c09)

Thank you! :)

**Comment by yf1019** [comment]
Hi, I just checked and find the code works well. May I check if you are using the 0.png image in the ./load/mv_instantmesh as the reference image?
![image](https://github.com/magic-research/magic-boost/assets/44568791/f9f57be0-5ea5-4ea1-ad8d-38046501902a)

**Comment by snowflakewang** [comment]
Oh, thank you for your guidance!! I make a mistake here. I use the initial input image of **InstantMesh** here. Thank you for your patient instruction. I revise my mistake and the code works well now.

Thanks a lot! :)

**Comment by yf1019** [comment]
Hi, thanks a lot for the bug reports. I have updated the REAMDE to make it clear.
