### ISSUE TITLE
Object gets a lot of artifacts during refinement

### ISSUE THREAD

**Issue by jclarkk** [magic-research/magic-boost#4]
The coarse seems fine:

https://github.com/magic-research/magic-boost/assets/6411191/bbb429c4-3fec-4b37-b647-d88fb51dce50

But here is the refined:

https://github.com/magic-research/magic-boost/assets/6411191/1f9ec697-8e88-40fc-9622-a9220b614081

I've pulled the latest fixes you've done in the README.

**Comment by yf1019** [comment]
Hi this is strange. Have you checked the setting of reference image? And make sure you select the right config for instantmesh.
![image](https://github.com/magic-research/magic-boost/assets/44568791/c27a3266-5abe-48e6-829e-15fa83276ab4)

**Comment by jclarkk** [comment]
Yes, here are the commands I've used:

`python launch.py --gpu 0 --config ./configs/mesh-fitting-instantmesh.yaml --train tag=test_stand system.guidance.geometry.shape_init=./load/mesh_instantmesh/c97fffac547a464aa3fc6088223c31c4/c97fffac547a464aa3fc6088223c31c4.obj`

`PYTHONPATH=$PYTHONPATH:./extern/MVC python launch.py --gpu 0 --config ./configs/refine_instantmesh.yaml --train tag=test_stand system.prompt_processor.prompt="a nightstand" data.mvcond_dir=./load/mv_instantmesh/c97fffac547a464aa3fc6088223c31c4 data.image_path=./load/mv_instantmesh/c97fffac547a464aa3fc6088223c31c4/0.png system.weights=/home/jonathan/Dev/magic-boost/outputs/mesh-fitting-nerf-instantmesh/test_stand@20240528-094158/ckpts/last.ckpt data.random_camera.batch_size=1`

`PYTHONPATH=$PYTHONPATH:./extern/MVC python launch.py --config /home/jonathan/Dev/magic-boost/outputs/refine-instantmesh/test_stand@20240528-094542/configs/parsed.yaml --export --gpu 0 resume=/home/jonathan/Dev/magic-boost/outputs/refine-instantmesh/test_stand@20240528-094542/ckpts/last.ckpt system.exporter_type=mesh-exporter system.geometry.isosurface_method=mc-cpu system.geometry.isosurface_resolution=256`

**Comment by yf1019** [comment]
The command looks right. Can you provide the input image here? I'll do a test.

**Comment by jclarkk** [comment]
Sure.
![437f30198b174e66a32d0bd889da9406](https://github.com/magic-research/magic-boost/assets/6411191/2d9a9e43-2e36-426e-b0ce-f97151927605)

**Comment by yf1019** [comment]
Hi, for this case the generated mv image filling up the entire picture, which is different from our training data. This may have caused the problem. We will fix this later. 
![check](https://github.com/magic-research/magic-boost/assets/44568791/7094f912-0cbe-4c45-ac5a-9e6288959428)

https://github.com/magic-research/magic-boost/assets/44568791/5f415b8b-9698-4ebd-941c-77d9da284035

**Comment by jclarkk** [comment]
Got it. Thanks for the prompt responses!

**Comment by abrar-khan-368** [comment]
Uploading it1000-test.mp4…

I tried the command as mentioned but getting the artifacts on refined mesh


https://github.com/magic-research/magic-boost/assets/64834623/1b276f72-2ba3-4316-81b9-0cd95dd2b07f
![sd_3_2](https://github.com/magic-research/magic-boost/assets/64834623/f37138d7-3df6-42f5-9bee-468cf4238fbb)
