### ISSUE TITLE
conditioning images

### ISSUE THREAD

**Issue by dmw1219** [magic-research/magic-boost#9]
<img width="1065" alt="image" src="https://github.com/magic-research/magic-boost/assets/20897420/a3982484-219e-4de8-bbcb-a536923fdf0a">
The notes in the refine stage says that the model uses the first image in the multi-view condition set as the reference image. Does it mean the other views images were not used during the refine stage?

**Comment by yf1019** [comment]
Hi, thanks for your interest. We use all the multi-view images at the refinement stage. By default, we adopt all the condition image as inputs to the multi-view diffusion model, which is set here:
![image](https://github.com/magic-research/magic-boost/assets/44568791/a8165a0f-c26b-424e-8b83-df585cea8971)

In addition, we adopt the first image in the multi-view input to provide another reference supervision:
https://code.byted.org/fan.yang123/magic-boost-threestudio-open/blob/master/threestudio/systems/magicboost.py#L212
